//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::AcceptAuthority;
use bitflip_program_client::instructions::AcceptAuthorityInstructionData;

#[derive(Debug, Args)]
pub struct AcceptAuthorityArgs {
	/// The `pending_authority` account [default: payer]
	#[arg(long)]
	pending_authority: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
}

pub(crate) fn run(context: &CliContext, args: AcceptAuthorityArgs) -> Result<(), CliError> {
	let pending_authority = match &args.pending_authority {
		Some(value) => CliContext::pubkey("--pending_authority", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let data =
		AcceptAuthorityInstructionData::new(|_data| {}).map_err(|_| CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		})?;

	let accounts = AcceptAuthority {
		pending_authority,
		config,
	};

	context.send(accounts.instruction(data))
}
