//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::ClaimSection;
use bitflip_program_client::instructions::ClaimSectionInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct ClaimSectionArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	#[arg(long)]
	bump: u8,
	#[arg(long)]
	maximum_price_lamports: u64,
	/// The `owner` account [default: payer]
	#[arg(long)]
	owner: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
	/// The `game` account
	#[arg(long)]
	game: String,
	/// The `previous_section` account
	#[arg(long)]
	previous_section: String,
	/// The `section` account
	#[arg(long)]
	section: String,
	/// The `treasury` account
	#[arg(long)]
	treasury: String,
}

pub(crate) fn run(context: &CliContext, args: ClaimSectionArgs) -> Result<(), CliError> {
	let owner = match &args.owner {
		Some(value) => CliContext::pubkey("--owner", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let game = CliContext::pubkey("--game", &args.game)?;
	let previous_section = CliContext::pubkey("--previous_section", &args.previous_section)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let treasury = CliContext::pubkey("--treasury", &args.treasury)?;
	let data = ClaimSectionInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
		data.bump = args.bump;
		data.maximum_price_lamports.set(args.maximum_price_lamports);
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = ClaimSection {
		owner,
		config,
		game,
		previous_section,
		section,
		treasury,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
