//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::ConfigureSectionPolicy;
use bitflip_program_client::instructions::ConfigureSectionPolicyInstructionData;

#[derive(Debug, Args)]
pub struct ConfigureSectionPolicyArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	#[arg(long)]
	expected_policy_version: u64,
	#[arg(long)]
	mode: u8,
	#[arg(long)]
	palette_id: u8,
	#[arg(long)]
	reward_policy: u8,
	#[arg(long)]
	starts_at: i64,
	#[arg(long)]
	ends_at: i64,
	#[arg(long)]
	entry_price_tokens: u64,
	#[arg(long)]
	reward_per_action_tokens: u64,
	#[arg(long)]
	rules_digest: String,
	/// The `owner` account [default: payer]
	#[arg(long)]
	owner: Option<String>,
	/// The `section` account
	#[arg(long)]
	section: String,
}

pub(crate) fn run(context: &CliContext, args: ConfigureSectionPolicyArgs) -> Result<(), CliError> {
	let rules_digest = CliContext::bytes::<32>("--rules_digest", &args.rules_digest)?;
	let owner = match &args.owner {
		Some(value) => CliContext::pubkey("--owner", value)?,
		None => context.payer_pubkey(),
	};
	let section = CliContext::pubkey("--section", &args.section)?;
	let data = ConfigureSectionPolicyInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
		data.expected_policy_version
			.set(args.expected_policy_version);
		data.mode = args.mode;
		data.palette_id = args.palette_id;
		data.reward_policy = args.reward_policy;
		data.starts_at.set(args.starts_at);
		data.ends_at.set(args.ends_at);
		data.entry_price_tokens.set(args.entry_price_tokens);
		data.reward_per_action_tokens
			.set(args.reward_per_action_tokens);
		data.rules_digest = rules_digest;
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = ConfigureSectionPolicy { owner, section };

	context.send(accounts.instruction(data))
}
