//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::ConfigureBitCustody;
use bitflip_program_client::instructions::ConfigureBitCustodyInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct ConfigureBitCustodyArgs {
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
	/// The `bit_mint` account
	#[arg(long)]
	bit_mint: String,
	/// The `bit_reserve` account
	#[arg(long)]
	bit_reserve: String,
}

pub(crate) fn run(context: &CliContext, args: ConfigureBitCustodyArgs) -> Result<(), CliError> {
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let bit_mint = CliContext::pubkey("--bit_mint", &args.bit_mint)?;
	let bit_reserve = CliContext::pubkey("--bit_reserve", &args.bit_reserve)?;
	let data =
		ConfigureBitCustodyInstructionData::new(|_data| {}).map_err(|_| CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		})?;

	let accounts = ConfigureBitCustody {
		authority,
		config,
		bit_mint,
		bit_reserve,
		token_program: Pubkey::from_str_const("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
	};

	context.send(accounts.instruction(data))
}
