//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::FlipPixels;
use bitflip_program_client::instructions::FlipPixelsInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct FlipPixelsArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	#[arg(long)]
	count: u8,
	#[arg(long)]
	coordinates: String,
	#[arg(long)]
	colour: u8,
	#[arg(long)]
	expected_policy_version: u64,
	#[arg(long)]
	expected_window_id: u64,
	#[arg(long)]
	maximum_unit_price_lamports: u64,
	#[arg(long)]
	maximum_total_price_lamports: u64,
	#[arg(long)]
	minimum_reward_tokens: u64,
	/// The `player` account [default: payer]
	#[arg(long)]
	player: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
	/// The `game` account
	#[arg(long)]
	game: String,
	/// The `section` account
	#[arg(long)]
	section: String,
	/// The `bit_mint` account
	#[arg(long)]
	bit_mint: String,
	/// The `section_vault` account
	#[arg(long)]
	section_vault: String,
	/// The `player_bit_account` account
	#[arg(long)]
	player_bit_account: String,
	/// The `token_program` account
	#[arg(long)]
	token_program: String,
}

pub(crate) fn run(context: &CliContext, args: FlipPixelsArgs) -> Result<(), CliError> {
	let coordinates = CliContext::bytes::<32>("--coordinates", &args.coordinates)?;
	let player = match &args.player {
		Some(value) => CliContext::pubkey("--player", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let game = CliContext::pubkey("--game", &args.game)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let bit_mint = CliContext::pubkey("--bit_mint", &args.bit_mint)?;
	let section_vault = CliContext::pubkey("--section_vault", &args.section_vault)?;
	let player_bit_account = CliContext::pubkey("--player_bit_account", &args.player_bit_account)?;
	let token_program = CliContext::pubkey("--token_program", &args.token_program)?;
	let data = FlipPixelsInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
		data.count = args.count;
		data.coordinates = coordinates;
		data.colour = args.colour;
		data.expected_policy_version
			.set(args.expected_policy_version);
		data.expected_window_id.set(args.expected_window_id);
		data.maximum_unit_price_lamports
			.set(args.maximum_unit_price_lamports);
		data.maximum_total_price_lamports
			.set(args.maximum_total_price_lamports);
		data.minimum_reward_tokens.set(args.minimum_reward_tokens);
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = FlipPixels {
		player,
		config,
		game,
		section,
		bit_mint,
		section_vault,
		player_bit_account,
		token_program,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
