//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::FundSectionVault;
use bitflip_program_client::instructions::FundSectionVaultInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct FundSectionVaultArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	/// The `funder` account [default: payer]
	#[arg(long)]
	funder: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
	/// The `section` account
	#[arg(long)]
	section: String,
	/// The `bit_mint` account
	#[arg(long)]
	bit_mint: String,
	/// The `bit_reserve` account
	#[arg(long)]
	bit_reserve: String,
	/// The `section_vault` account
	#[arg(long)]
	section_vault: String,
}

pub(crate) fn run(context: &CliContext, args: FundSectionVaultArgs) -> Result<(), CliError> {
	let funder = match &args.funder {
		Some(value) => CliContext::pubkey("--funder", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let bit_mint = CliContext::pubkey("--bit_mint", &args.bit_mint)?;
	let bit_reserve = CliContext::pubkey("--bit_reserve", &args.bit_reserve)?;
	let section_vault = CliContext::pubkey("--section_vault", &args.section_vault)?;
	let data = FundSectionVaultInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = FundSectionVault {
		funder,
		config,
		section,
		bit_mint,
		bit_reserve,
		section_vault,
		associated_token_program: Pubkey::from_str_const(
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
		),
		token_program: Pubkey::from_str_const("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
