//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::InitializeGame;
use bitflip_program_client::instructions::InitializeGameInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct InitializeGameArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	#[arg(long)]
	game_bump: u8,
	#[arg(long)]
	section_bump: u8,
	/// The `payer` account [default: payer]
	#[arg(long)]
	payer: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
	/// The `game` account
	#[arg(long)]
	game: String,
	/// The `section` account
	#[arg(long)]
	section: String,
}

pub(crate) fn run(context: &CliContext, args: InitializeGameArgs) -> Result<(), CliError> {
	let payer = match &args.payer {
		Some(value) => CliContext::pubkey("--payer", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let game = CliContext::pubkey("--game", &args.game)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let data = InitializeGameInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
		data.game_bump = args.game_bump;
		data.section_bump = args.section_bump;
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = InitializeGame {
		payer,
		config,
		game,
		section,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
