//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::InitializeConfig;
use bitflip_program_client::instructions::InitializeConfigInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct InitializeConfigArgs {
	#[arg(long)]
	bump: u8,
	/// The `payer` account [default: payer]
	#[arg(long)]
	payer: Option<String>,
	/// The `config` account [default: derived]
	#[arg(long)]
	config: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: InitializeConfigArgs) -> Result<(), CliError> {
	let payer = match &args.payer {
		Some(value) => CliContext::pubkey("--payer", value)?,
		None => context.payer_pubkey(),
	};
	let config = match &args.config {
		Some(value) => CliContext::pubkey("--config", value)?,
		None => Pubkey::find_program_address(&["config".as_bytes()], &context.program_address).0,
	};
	let data = InitializeConfigInstructionData::new(|data| {
		data.bump = args.bump;
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = InitializeConfig {
		payer,
		config,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
