//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

pub mod accept_authority;
pub mod cancel_section_listing;
pub mod claim_section;
pub mod configure_bit_custody;
pub mod configure_section_policy;
pub mod flip_pixels;
pub mod fund_section_vault;
pub mod initialize_config;
pub mod initialize_game;
pub mod list_section;
pub mod propose_authority;
pub mod purchase_section;
pub mod record_section_mint;
pub mod seal_section;
pub mod settle_section_economy;
pub mod update_config;
pub mod withdraw_section_owner_fees;

pub use accept_authority::AcceptAuthorityArgs;
pub use cancel_section_listing::CancelSectionListingArgs;
pub use claim_section::ClaimSectionArgs;
pub use configure_bit_custody::ConfigureBitCustodyArgs;
pub use configure_section_policy::ConfigureSectionPolicyArgs;
pub use flip_pixels::FlipPixelsArgs;
pub use fund_section_vault::FundSectionVaultArgs;
pub use initialize_config::InitializeConfigArgs;
pub use initialize_game::InitializeGameArgs;
pub use list_section::ListSectionArgs;
pub use propose_authority::ProposeAuthorityArgs;
pub use purchase_section::PurchaseSectionArgs;
pub use record_section_mint::RecordSectionMintArgs;
pub use seal_section::SealSectionArgs;
pub use settle_section_economy::SettleSectionEconomyArgs;
pub use update_config::UpdateConfigArgs;
pub use withdraw_section_owner_fees::WithdrawSectionOwnerFeesArgs;
