//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::ProposeAuthority;
use bitflip_program_client::instructions::ProposeAuthorityInstructionData;

#[derive(Debug, Args)]
pub struct ProposeAuthorityArgs {
	#[arg(long)]
	pending_authority: String,
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
}

pub(crate) fn run(context: &CliContext, args: ProposeAuthorityArgs) -> Result<(), CliError> {
	let pending_authority = CliContext::pubkey("--pending_authority", &args.pending_authority)?;
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let data = ProposeAuthorityInstructionData::new(|data| {
		data.pending_authority = pending_authority;
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = ProposeAuthority { authority, config };

	context.send(accounts.instruction(data))
}
