//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::PurchaseSection;
use bitflip_program_client::instructions::PurchaseSectionInstructionData;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Args)]
pub struct PurchaseSectionArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	#[arg(long)]
	maximum_price_lamports: u64,
	/// The `buyer` account [default: payer]
	#[arg(long)]
	buyer: Option<String>,
	/// The `seller` account
	#[arg(long)]
	seller: String,
	/// The `game` account
	#[arg(long)]
	game: String,
	/// The `section` account
	#[arg(long)]
	section: String,
}

pub(crate) fn run(context: &CliContext, args: PurchaseSectionArgs) -> Result<(), CliError> {
	let buyer = match &args.buyer {
		Some(value) => CliContext::pubkey("--buyer", value)?,
		None => context.payer_pubkey(),
	};
	let seller = CliContext::pubkey("--seller", &args.seller)?;
	let game = CliContext::pubkey("--game", &args.game)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let data = PurchaseSectionInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
		data.maximum_price_lamports.set(args.maximum_price_lamports);
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = PurchaseSection {
		buyer,
		seller,
		game,
		section,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
