//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::RecordSectionMint;
use bitflip_program_client::instructions::RecordSectionMintInstructionData;

#[derive(Debug, Args)]
pub struct RecordSectionMintArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	#[arg(long)]
	expected_owner: String,
	#[arg(long)]
	asset_id: String,
	#[arg(long)]
	merkle_tree: String,
	#[arg(long)]
	leaf_index: u32,
	/// The `collection_authority` account [default: payer]
	#[arg(long)]
	collection_authority: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
	/// The `game` account
	#[arg(long)]
	game: String,
	/// The `section` account
	#[arg(long)]
	section: String,
}

pub(crate) fn run(context: &CliContext, args: RecordSectionMintArgs) -> Result<(), CliError> {
	let expected_owner = CliContext::pubkey("--expected_owner", &args.expected_owner)?;
	let asset_id = CliContext::pubkey("--asset_id", &args.asset_id)?;
	let merkle_tree = CliContext::pubkey("--merkle_tree", &args.merkle_tree)?;
	let collection_authority = match &args.collection_authority {
		Some(value) => CliContext::pubkey("--collection_authority", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let game = CliContext::pubkey("--game", &args.game)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let data = RecordSectionMintInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
		data.expected_owner = expected_owner;
		data.asset_id = asset_id;
		data.merkle_tree = merkle_tree;
		data.leaf_index.set(args.leaf_index);
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = RecordSectionMint {
		collection_authority,
		config,
		game,
		section,
	};

	context.send(accounts.instruction(data))
}
