//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::SettleSectionEconomy;
use bitflip_program_client::instructions::SettleSectionEconomyInstructionData;

#[derive(Debug, Args)]
pub struct SettleSectionEconomyArgs {
	#[arg(long)]
	game_index: u8,
	#[arg(long)]
	section_index: u8,
	/// The `game` account
	#[arg(long)]
	game: String,
	/// The `section` account
	#[arg(long)]
	section: String,
}

pub(crate) fn run(context: &CliContext, args: SettleSectionEconomyArgs) -> Result<(), CliError> {
	let game = CliContext::pubkey("--game", &args.game)?;
	let section = CliContext::pubkey("--section", &args.section)?;
	let data = SettleSectionEconomyInstructionData::new(|data| {
		data.game_index = args.game_index;
		data.section_index = args.section_index;
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = SettleSectionEconomy { game, section };

	context.send(accounts.instruction(data))
}
