//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;

use crate::context::CliContext;
use crate::context::CliError;
use bitflip_program_client::instructions::UpdateConfig;
use bitflip_program_client::instructions::UpdateConfigInstructionData;

#[derive(Debug, Args)]
pub struct UpdateConfigArgs {
	#[arg(long)]
	treasury: String,
	#[arg(long)]
	collection_authority: String,
	#[arg(long)]
	claim_price_lamports: u64,
	#[arg(long)]
	flip_fee_lamports: u64,
	#[arg(long)]
	minimum_flip_fee_lamports: u64,
	#[arg(long)]
	maximum_flip_fee_lamports: u64,
	#[arg(long)]
	unlock_interval_seconds: u32,
	#[arg(long)]
	early_unlock_flips: u32,
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `config` account
	#[arg(long)]
	config: String,
}

pub(crate) fn run(context: &CliContext, args: UpdateConfigArgs) -> Result<(), CliError> {
	let treasury = CliContext::pubkey("--treasury", &args.treasury)?;
	let collection_authority =
		CliContext::pubkey("--collection_authority", &args.collection_authority)?;
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let config = CliContext::pubkey("--config", &args.config)?;
	let data = UpdateConfigInstructionData::new(|data| {
		data.treasury = treasury;
		data.collection_authority = collection_authority;
		data.claim_price_lamports.set(args.claim_price_lamports);
		data.flip_fee_lamports.set(args.flip_fee_lamports);
		data.minimum_flip_fee_lamports
			.set(args.minimum_flip_fee_lamports);
		data.maximum_flip_fee_lamports
			.set(args.maximum_flip_fee_lamports);
		data.unlock_interval_seconds
			.set(args.unlock_interval_seconds);
		data.early_unlock_flips.set(args.early_unlock_flips);
	})
	.map_err(|_| CliError::InvalidData {
		message: "instruction data rejected the provided arguments".to_string(),
	})?;

	let accounts = UpdateConfig { authority, config };

	context.send(accounts.instruction(data))
}
