[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bitflip = "ERteNUqr6wFmKkKf94gBYCJ5vZMZUCWzrnkVHAJdePvB"

[programs.testnet]
bitflip = "ERteNUqr6wFmKkKf94gBYCJ5vZMZUCWzrnkVHAJdePvB"

[programs.devnet]
bitflip = "ERteNUqr6wFmKkKf94gBYCJ5vZMZUCWzrnkVHAJdePvB"

[programs.mainnet]
bitflip = "ERteNUqr6wFmKkKf94gBYCJ5vZMZUCWzrnkVHAJdePvB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./setup/keypairs/admin.json"

[workspace]
members = ["bitflip_program"]

[scripts]
test = "echo hello"

[test]
startup_wait = 100000
shutdown_wait = 2000
upgradeable = false
