[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bitflip = "5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM"

[programs.testnet]
bitflip = "5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM"

[programs.devnet]
bitflip = "5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM"

[programs.mainnet]
bitflip = "5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./setup/keypairs/admin.json"

[workspace]
members = ["bitflip_legacy_program"]

[scripts]
test = "echo hello"

[test]
startup_wait = 100000
shutdown_wait = 2000
upgradeable = false
