[tasks."watch:bitflip"]
run_task = { name = ["watch:bitflip:leptos", "watch:bitflip:tailwind"], parallel = true, fork = true }

[tasks."watch:bitflip:leptos"]
dependencies = ["build:bitflip:tailwind"]
command = "cargo"
args = ["leptos", "watch", "--hot-reload", "--project", "bitflip"]

[tasks."watch:bitflip:tailwind"]
command = "deno"
args = ["task", "tailwind:watch"]

[tasks."build:bitflip:tailwind"]
command = "deno"
args = ["task", "tailwind:build"]

[config]
default_to_workspace = false
