//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use clap::Subcommand;
use serde_json::Value;
use serde_json::json;

use crate::context::CliContext;
use crate::context::CliError;
use solana_sdk::pubkey::Pubkey;

#[derive(Debug, Subcommand)]
pub enum Command {
	ConfigState(ConfigStateArgs),

	GameState(GameStateArgs),

	SectionState(SectionStateArgs),
}

#[derive(Debug, Args)]
pub struct ConfigStateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
}

#[derive(Debug, Args)]
pub struct GameStateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `game_index`.
	#[arg(long)]
	game_index: Option<u8>,
}

#[derive(Debug, Args)]
pub struct SectionStateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `game_index`.
	#[arg(long)]
	game_index: Option<u8>,
	/// PDA seed `section_index`.
	#[arg(long)]
	section_index: Option<u8>,
}

pub(crate) fn run(context: &CliContext, command: Command) -> Result<(), CliError> {
	match command {
		Command::ConfigState(args) => fetch_config_state(context, args),
		Command::GameState(args) => fetch_game_state(context, args),
		Command::SectionState(args) => fetch_section_state(context, args),
	}
}

fn fetch_config_state(context: &CliContext, args: ConfigStateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let seeds: &[&[u8]] = &["config".as_bytes()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match bitflip_program_client::accounts::ConfigState::from_bytes(&data) {
		Ok(account) => config_state_json(account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "config-state", &address, &value);
	Ok(())
}

fn fetch_game_state(context: &CliContext, args: GameStateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let game_index = args.game_index.ok_or_else(|| CliError::MissingSeed {
				account: "game-state".to_string(),
				seed: "--game_index".to_string(),
			})?;
			let game_index_bytes = game_index.to_le_bytes();
			let seeds: &[&[u8]] = &["game".as_bytes(), game_index_bytes.as_ref()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match bitflip_program_client::accounts::GameState::from_bytes(&data) {
		Ok(account) => game_state_json(account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "game-state", &address, &value);
	Ok(())
}

fn fetch_section_state(context: &CliContext, args: SectionStateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let game_index = args.game_index.ok_or_else(|| CliError::MissingSeed {
				account: "section-state".to_string(),
				seed: "--game_index".to_string(),
			})?;
			let section_index = args.section_index.ok_or_else(|| CliError::MissingSeed {
				account: "section-state".to_string(),
				seed: "--section_index".to_string(),
			})?;
			let game_index_bytes = game_index.to_le_bytes();
			let section_index_bytes = section_index.to_le_bytes();
			let seeds: &[&[u8]] = &[
				"section".as_bytes(),
				game_index_bytes.as_ref(),
				section_index_bytes.as_ref(),
			];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match bitflip_program_client::accounts::SectionState::from_bytes(&data) {
		Ok(account) => section_state_json(account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "section-state", &address, &value);
	Ok(())
}

fn config_state_json(account: &bitflip_program_client::accounts::ConfigStateZc) -> Value {
	json!({
		"version": account.version,
		"authority": account.authority.to_string(),
		"pending_authority": account.pending_authority.to_string(),
		"treasury": account.treasury.to_string(),
		"collection_authority": account.collection_authority.to_string(),
		"bit_mint": account.bit_mint.to_string(),
		"bit_reserve": account.bit_reserve.to_string(),
		"claim_price_lamports": account.claim_price_lamports.get(),
		"flip_fee_lamports": account.flip_fee_lamports.get(),
		"minimum_flip_fee_lamports": account.minimum_flip_fee_lamports.get(),
		"maximum_flip_fee_lamports": account.maximum_flip_fee_lamports.get(),
		"unlock_interval_seconds": account.unlock_interval_seconds.get(),
		"early_unlock_flips": account.early_unlock_flips.get(),
		"game_count": account.game_count.get(),
		"bump": account.bump,
	})
}

fn game_state_json(account: &bitflip_program_client::accounts::GameStateZc) -> Value {
	json!({
		"game_index": account.game_index,
		"status": account.status,
		"bump": account.bump,
		"economy_version": account.economy_version,
		"starts_at": account.starts_at.get(),
		"next_section": account.next_section.get(),
		"minted_sections": account.minted_sections.get(),
		"flip_fee_lamports": account.flip_fee_lamports.get(),
		"total_flips": account.total_flips.get(),
		"section_allocation_tokens": account.section_allocation_tokens.get(),
		"emission_duration_seconds": account.emission_duration_seconds.get(),
		"window_seconds": account.window_seconds.get(),
		"target_tokens_per_window": account.target_tokens_per_window.get(),
		"start_price_lamports": account.start_price_lamports.get(),
		"minimum_price_lamports": account.minimum_price_lamports.get(),
		"maximum_price_lamports": account.maximum_price_lamports.get(),
		"start_floor_price_lamports": account.start_floor_price_lamports.get(),
		"end_floor_price_lamports": account.end_floor_price_lamports.get(),
		"change_denominator": account.change_denominator.get(),
		"burst_elasticity": account.burst_elasticity.get(),
		"owner_share_basis_points": account.owner_share_basis_points.get(),
	})
}

fn section_state_json(account: &bitflip_program_client::accounts::SectionStateZc) -> Value {
	json!({
		"owner": account.owner.to_string(),
		"asset_id": account.asset_id.to_string(),
		"merkle_tree": account.merkle_tree.to_string(),
		"bit_vault": account.bit_vault.to_string(),
		"game_index": account.game_index,
		"section_index": account.section_index,
		"status": account.status,
		"bump": account.bump,
		"on_pixels": account.on_pixels.get(),
		"leaf_index": account.leaf_index.get(),
		"flip_count": account.flip_count.get(),
		"revision": account.revision.get(),
		"last_flip_at": account.last_flip_at.get(),
		"sale_price_lamports": account.sale_price_lamports.get(),
		"economy_launched_at": account.economy_launched_at.get(),
		"economy_window_started_at": account.economy_window_started_at.get(),
		"economy_last_updated_at": account.economy_last_updated_at.get(),
		"economy_window_id": account.economy_window_id.get(),
		"economy_window_target_tokens": account.economy_window_target_tokens.get(),
		"economy_window_rewarded_tokens": account.economy_window_rewarded_tokens.get(),
		"emitted_tokens": account.emitted_tokens.get(),
		"reward_pool_tokens": account.reward_pool_tokens.get(),
		"controller_price_lamports": account.controller_price_lamports.get(),
		"posted_price_lamports": account.posted_price_lamports.get(),
		"protocol_fee_lamports": account.protocol_fee_lamports.get(),
		"owner_fee_lamports": account.owner_fee_lamports.get(),
		"policy_version": account.policy_version.get(),
		"policy_starts_at": account.policy_starts_at.get(),
		"policy_ends_at": account.policy_ends_at.get(),
		"policy_entry_price_tokens": account.policy_entry_price_tokens.get(),
		"policy_reward_per_action_tokens": account.policy_reward_per_action_tokens.get(),
		"policy_rules_digest": account.policy_rules_digest.iter().map(|byte| format!("{byte:02x}")).collect::<String>(),
		"policy_mode": account.policy_mode,
		"policy_palette_id": account.policy_palette_id,
		"policy_reward_policy": account.policy_reward_policy,
		"pixels": account.pixels.iter().map(|byte| format!("{byte:02x}")).collect::<String>(),
	})
}

fn print_value(json_output: bool, name: &str, address: &Pubkey, value: &Value) {
	if json_output {
		println!(
			"{}",
			serde_json::to_string_pretty(value).unwrap_or_default()
		);
		return;
	}

	println!("{name} {address}");
	if let Some(fields) = value.as_object() {
		for (key, value) in fields {
			println!("  {key}: {value}");
		}
	}
}
