//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

//! Generated CLI for the `bitflipProgram` program.

mod commands;
mod context;
mod fetch;
use clap::Parser;
use clap::Subcommand;
use context::CliContext;
use solana_sdk::pubkey::Pubkey;

/// Command-line interface for bitflipProgram
#[derive(Debug, Parser)]
#[command(name = "bitflip-program-cli", version = env!("CARGO_PKG_VERSION"), propagate_version = true)]
struct Cli {
	/// RPC endpoint: `mainnet`, `devnet`, `testnet`, `localhost`, or an https URL.
	#[arg(
		short = 'u',
		long,
		global = true,
		default_value = "devnet",
		env = "SOLANA_URL"
	)]
	url: String,

	/// Payer keypair file in the standard Solana JSON byte-array format.
	#[arg(
		short = 'k',
		long,
		global = true,
		default_value = "~/.config/solana/id.json",
		env = "PINA_KEYPAIR"
	)]
	keypair: String,

	/// Override the on-chain program address.
	#[arg(long, global = true)]
	program_id: Option<String>,

	/// Simulate the transaction and print its logs instead of sending.
	#[arg(long, global = true)]
	simulate: bool,

	/// Print machine-readable JSON output.
	#[arg(long, global = true)]
	json: bool,

	#[command(subcommand)]
	command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
	InitializeConfig(commands::InitializeConfigArgs),

	UpdateConfig(commands::UpdateConfigArgs),

	ProposeAuthority(commands::ProposeAuthorityArgs),

	AcceptAuthority(commands::AcceptAuthorityArgs),

	InitializeGame(commands::InitializeGameArgs),

	ClaimSection(commands::ClaimSectionArgs),

	FlipPixels(commands::FlipPixelsArgs),

	SealSection(commands::SealSectionArgs),

	RecordSectionMint(commands::RecordSectionMintArgs),

	ListSection(commands::ListSectionArgs),

	CancelSectionListing(commands::CancelSectionListingArgs),

	PurchaseSection(commands::PurchaseSectionArgs),

	SettleSectionEconomy(commands::SettleSectionEconomyArgs),

	ConfigureBitCustody(commands::ConfigureBitCustodyArgs),

	FundSectionVault(commands::FundSectionVaultArgs),

	WithdrawSectionOwnerFees(commands::WithdrawSectionOwnerFeesArgs),

	ConfigureSectionPolicy(commands::ConfigureSectionPolicyArgs),
	/// Fetch and decode a program account.
	#[command(subcommand)]
	Fetch(fetch::Command),
}

fn main() {
	let cli = Cli::parse();
	if let Err(error) = run(cli) {
		eprintln!("error: {error}");
		std::process::exit(1);
	}
}

fn run(cli: Cli) -> Result<(), context::CliError> {
	let program_address = match &cli.program_id {
		Some(value) => CliContext::pubkey("--program-id", value)?,
		None => Pubkey::from_str_const("5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM"),
	};
	let context = CliContext::new(
		&cli.url,
		&cli.keypair,
		program_address,
		cli.simulate,
		cli.json,
	)?;

	match cli.command {
		Command::InitializeConfig(args) => commands::initialize_config::run(&context, args),
		Command::UpdateConfig(args) => commands::update_config::run(&context, args),
		Command::ProposeAuthority(args) => commands::propose_authority::run(&context, args),
		Command::AcceptAuthority(args) => commands::accept_authority::run(&context, args),
		Command::InitializeGame(args) => commands::initialize_game::run(&context, args),
		Command::ClaimSection(args) => commands::claim_section::run(&context, args),
		Command::FlipPixels(args) => commands::flip_pixels::run(&context, args),
		Command::SealSection(args) => commands::seal_section::run(&context, args),
		Command::RecordSectionMint(args) => commands::record_section_mint::run(&context, args),
		Command::ListSection(args) => commands::list_section::run(&context, args),
		Command::CancelSectionListing(args) => {
			commands::cancel_section_listing::run(&context, args)
		}
		Command::PurchaseSection(args) => commands::purchase_section::run(&context, args),
		Command::SettleSectionEconomy(args) => {
			commands::settle_section_economy::run(&context, args)
		}
		Command::ConfigureBitCustody(args) => commands::configure_bit_custody::run(&context, args),
		Command::FundSectionVault(args) => commands::fund_section_vault::run(&context, args),
		Command::WithdrawSectionOwnerFees(args) => {
			commands::withdraw_section_owner_fees::run(&context, args)
		}
		Command::ConfigureSectionPolicy(args) => {
			commands::configure_section_policy::run(&context, args)
		}
		Command::Fetch(command) => fetch::run(&context, command),
	}
}
