[package]
name = "bitflip_cli"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "bitflip"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true , default-features = true }
bincode = { workspace = true }
bitflip_program = { workspace = true, features = ["no-entrypoint", "client", "ssr"] }
bitflip_program_test = { workspace = true, features = ["test_validator"] }
clap = { version = "4", features = ["derive"] }
colored = { workspace = true }
console = { workspace = true }
env_logger = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true , default-features = true }
serde_json = { workspace = true , default-features = true }
solana-program = { workspace = true , default-features = true }
solana-program-test = { workspace = true , default-features = true }
solana-sdk = { workspace = true , default-features = true }
test_utils_keypairs = { workspace = true , default-features = true }
test_utils_solana = { workspace = true, features = ["test_validator"] , default-features = true }
tokio = { workspace = true, features = ["macros", "rt"] , default-features = true }
url = { workspace = true , default-features = true }
wasm_client_solana = { workspace = true , default-features = true }

[dev-dependencies]
insta = { workspace = true, features = ["json", "redactions", "ron", "yaml"] , default-features = true }
test-log = { workspace = true, features = ["log", "trace"] , default-features = true }
tokio = { workspace = true, features = ["test-util", "rt", "macros", "time"] , default-features = true }

[lints]
workspace = true
