[alias]
# bins
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
insta = ["bin", "cargo-insta"]
leptos = ["bin", "cargo-leptos"]
mutants = ["bin", "cargo-mutants"]
make = ["bin", "cargo-make"]

test_program = ["nextest", "run", "-p", "bitflip_program", "-F", "ssr,client"]
test_program_validator = ["nextest", "run", "-p", "bitflip_program", "-F", "ssr,test_validator"]
test_bitflip_ssr = ["nextest", "run", "-p", "bitflip", "-F", "ssr"]
test_bitflip_js = ["nextest", "run", "-p", "bitflip", "-F", "hydrate"]
