//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations make`. Do not edit.
//!
//! Run `pina migrations make` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: f9fa119458d985136a57c7085ef9aa7fa1a698b7e246c894db1c59e1445ba6ff
// program-id: 5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM
// version-type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM";

/// ABI layout for the `ConfigState` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "a8a169d36bcdf336f831c9996466cbb1271cb7a0dd954f5f15967cbafbf6c1c5";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 236;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 236;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("version", MIGRATION_HEADER_SIZE + 0, 1),
		("authority", MIGRATION_HEADER_SIZE + 1, 32),
		("pending_authority", MIGRATION_HEADER_SIZE + 33, 32),
		("treasury", MIGRATION_HEADER_SIZE + 65, 32),
		("collection_authority", MIGRATION_HEADER_SIZE + 97, 32),
		("bit_mint", MIGRATION_HEADER_SIZE + 129, 32),
		("bit_reserve", MIGRATION_HEADER_SIZE + 161, 32),
		("claim_price_lamports", MIGRATION_HEADER_SIZE + 193, 8),
		("flip_fee_lamports", MIGRATION_HEADER_SIZE + 201, 8),
		("minimum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 209, 8),
		("maximum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 217, 8),
		("unlock_interval_seconds", MIGRATION_HEADER_SIZE + 225, 4),
		("early_unlock_flips", MIGRATION_HEADER_SIZE + 229, 4),
		("game_count", MIGRATION_HEADER_SIZE + 233, 2),
		("bump", MIGRATION_HEADER_SIZE + 235, 1),
	];
}

/// ABI layout for the `GameState` account.
pub mod account_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "GameState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "f8d9f10dd41208ebcd930a61f035d47be9317ea499096f0af06f5114603be57d";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 122;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 122;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("status", MIGRATION_HEADER_SIZE + 1, 1),
		("bump", MIGRATION_HEADER_SIZE + 2, 1),
		("economy_version", MIGRATION_HEADER_SIZE + 3, 1),
		("starts_at", MIGRATION_HEADER_SIZE + 4, 8),
		("next_section", MIGRATION_HEADER_SIZE + 12, 2),
		("minted_sections", MIGRATION_HEADER_SIZE + 14, 2),
		("flip_fee_lamports", MIGRATION_HEADER_SIZE + 16, 8),
		("total_flips", MIGRATION_HEADER_SIZE + 24, 8),
		("section_allocation_tokens", MIGRATION_HEADER_SIZE + 32, 8),
		("emission_duration_seconds", MIGRATION_HEADER_SIZE + 40, 8),
		("window_seconds", MIGRATION_HEADER_SIZE + 48, 8),
		("target_tokens_per_window", MIGRATION_HEADER_SIZE + 56, 8),
		("start_price_lamports", MIGRATION_HEADER_SIZE + 64, 8),
		("minimum_price_lamports", MIGRATION_HEADER_SIZE + 72, 8),
		("maximum_price_lamports", MIGRATION_HEADER_SIZE + 80, 8),
		("start_floor_price_lamports", MIGRATION_HEADER_SIZE + 88, 8),
		("end_floor_price_lamports", MIGRATION_HEADER_SIZE + 96, 8),
		("change_denominator", MIGRATION_HEADER_SIZE + 104, 8),
		("burst_elasticity", MIGRATION_HEADER_SIZE + 112, 8),
		("owner_share_basis_points", MIGRATION_HEADER_SIZE + 120, 2),
	];
}

/// ABI layout for the `SectionState` account.
pub mod account_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SectionState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "d95ca43ba5062b20941ad07c40713d42dbbdc7c5b715003ee80e4231c4a33f54";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 853;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 853;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("owner", MIGRATION_HEADER_SIZE + 0, 32),
		("asset_id", MIGRATION_HEADER_SIZE + 32, 32),
		("merkle_tree", MIGRATION_HEADER_SIZE + 64, 32),
		("bit_vault", MIGRATION_HEADER_SIZE + 96, 32),
		("game_index", MIGRATION_HEADER_SIZE + 128, 1),
		("section_index", MIGRATION_HEADER_SIZE + 129, 1),
		("status", MIGRATION_HEADER_SIZE + 130, 1),
		("bump", MIGRATION_HEADER_SIZE + 131, 1),
		("on_pixels", MIGRATION_HEADER_SIZE + 132, 2),
		("leaf_index", MIGRATION_HEADER_SIZE + 134, 4),
		("flip_count", MIGRATION_HEADER_SIZE + 138, 8),
		("revision", MIGRATION_HEADER_SIZE + 146, 8),
		("last_flip_at", MIGRATION_HEADER_SIZE + 154, 8),
		("sale_price_lamports", MIGRATION_HEADER_SIZE + 162, 8),
		("economy_launched_at", MIGRATION_HEADER_SIZE + 170, 8),
		("economy_window_started_at", MIGRATION_HEADER_SIZE + 178, 8),
		("economy_last_updated_at", MIGRATION_HEADER_SIZE + 186, 8),
		("economy_window_id", MIGRATION_HEADER_SIZE + 194, 8),
		("economy_window_target_tokens", MIGRATION_HEADER_SIZE + 202, 8),
		("economy_window_rewarded_tokens", MIGRATION_HEADER_SIZE + 210, 8),
		("emitted_tokens", MIGRATION_HEADER_SIZE + 218, 8),
		("reward_pool_tokens", MIGRATION_HEADER_SIZE + 226, 8),
		("controller_price_lamports", MIGRATION_HEADER_SIZE + 234, 8),
		("posted_price_lamports", MIGRATION_HEADER_SIZE + 242, 8),
		("protocol_fee_lamports", MIGRATION_HEADER_SIZE + 250, 8),
		("owner_fee_lamports", MIGRATION_HEADER_SIZE + 258, 8),
		("policy_version", MIGRATION_HEADER_SIZE + 266, 8),
		("policy_starts_at", MIGRATION_HEADER_SIZE + 274, 8),
		("policy_ends_at", MIGRATION_HEADER_SIZE + 282, 8),
		("policy_entry_price_tokens", MIGRATION_HEADER_SIZE + 290, 8),
		("policy_reward_per_action_tokens", MIGRATION_HEADER_SIZE + 298, 8),
		("policy_rules_digest", MIGRATION_HEADER_SIZE + 306, 32),
		("policy_mode", MIGRATION_HEADER_SIZE + 338, 1),
		("policy_palette_id", MIGRATION_HEADER_SIZE + 339, 1),
		("policy_reward_policy", MIGRATION_HEADER_SIZE + 340, 1),
		("pixels", MIGRATION_HEADER_SIZE + 341, 512),
	];
}

/// ABI layout for the `ColourPixelsFlippedEvent` event.
pub mod event_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ColourPixelsFlippedEvent";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "2711a7699d390c1fb0bc4ab78de90b51c8ddf381ef23c5c166d611d403cb090a";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 84;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 84;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("player", MIGRATION_HEADER_SIZE + 0, 32),
		("policy_version", MIGRATION_HEADER_SIZE + 32, 8),
		("revision", MIGRATION_HEADER_SIZE + 40, 8),
		("coordinates", MIGRATION_HEADER_SIZE + 48, 32),
		("game_index", MIGRATION_HEADER_SIZE + 80, 1),
		("section_index", MIGRATION_HEADER_SIZE + 81, 1),
		("count", MIGRATION_HEADER_SIZE + 82, 1),
		("colour", MIGRATION_HEADER_SIZE + 83, 1),
	];
}

/// ABI layout for the `InitializeConfigInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializeConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "43124b1aa7c67081addd4259a24fbc507a54bca9953fea6e38dadfaceee4a8ef";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 1;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 1;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
	];
}

/// ABI layout for the `UpdateConfigInstruction` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "UpdateConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "9e4c2a54ebad1f3fccab776dd697bb6643124f3b9bdadcae6df477c7b22ba34c";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 104;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 104;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("treasury", MIGRATION_HEADER_SIZE + 0, 32),
		("collection_authority", MIGRATION_HEADER_SIZE + 32, 32),
		("claim_price_lamports", MIGRATION_HEADER_SIZE + 64, 8),
		("flip_fee_lamports", MIGRATION_HEADER_SIZE + 72, 8),
		("minimum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 80, 8),
		("maximum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 88, 8),
		("unlock_interval_seconds", MIGRATION_HEADER_SIZE + 96, 4),
		("early_unlock_flips", MIGRATION_HEADER_SIZE + 100, 4),
	];
}

/// ABI layout for the `ProposeAuthorityInstruction` instruction.
pub mod instruction_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ProposeAuthorityInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4db9826e83aa18a77ea93093624f4c047ba097e57fdb2bec6d074171079ebf27";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 32;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 32;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("pending_authority", MIGRATION_HEADER_SIZE + 0, 32),
	];
}

/// ABI layout for the `AcceptAuthorityInstruction` instruction.
pub mod instruction_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "AcceptAuthorityInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "0964b5ff00a94fb98f2536839ca6abc68a04f31d844cbac2a3aa627a73eeca5a";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `InitializeGameInstruction` instruction.
pub mod instruction_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializeGameInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "1ce66c1e59793d7d31eb415e649f8568bb5de8ed458c9ab53b189d3a3ada5f72";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 4;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 4;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("game_bump", MIGRATION_HEADER_SIZE + 2, 1),
		("section_bump", MIGRATION_HEADER_SIZE + 3, 1),
	];
}

/// ABI layout for the `ClaimSectionInstruction` instruction.
pub mod instruction_1_05 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:05";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ClaimSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "f4267a714f07d205a0189b7f46c92ac49d4c1c00ae269c1854d8c2a849eb8c59";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 11;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 11;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("bump", MIGRATION_HEADER_SIZE + 2, 1),
		("maximum_price_lamports", MIGRATION_HEADER_SIZE + 3, 8),
	];
}

/// ABI layout for the `FlipPixelsInstruction` instruction.
pub mod instruction_1_06 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:06";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "FlipPixelsInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "214ee311dc41242129b47ef8370716a9662a54030ae427d9087e04d1ce81942f";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 76;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 76;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("count", MIGRATION_HEADER_SIZE + 2, 1),
		("coordinates", MIGRATION_HEADER_SIZE + 3, 32),
		("colour", MIGRATION_HEADER_SIZE + 35, 1),
		("expected_policy_version", MIGRATION_HEADER_SIZE + 36, 8),
		("expected_window_id", MIGRATION_HEADER_SIZE + 44, 8),
		("maximum_unit_price_lamports", MIGRATION_HEADER_SIZE + 52, 8),
		("maximum_total_price_lamports", MIGRATION_HEADER_SIZE + 60, 8),
		("minimum_reward_tokens", MIGRATION_HEADER_SIZE + 68, 8),
	];
}

/// ABI layout for the `SealSectionInstruction` instruction.
pub mod instruction_1_07 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:07";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SealSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "982e19417c9c992dfbba5efdaebea28d011f34f4adfd2c0332fa73cacc593838";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `RecordSectionMintInstruction` instruction.
pub mod instruction_1_08 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:08";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "RecordSectionMintInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "acba0d4fa70dc0a638229a131147783b34a178de5630416aef5ee9521dd95192";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 102;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 102;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("expected_owner", MIGRATION_HEADER_SIZE + 2, 32),
		("asset_id", MIGRATION_HEADER_SIZE + 34, 32),
		("merkle_tree", MIGRATION_HEADER_SIZE + 66, 32),
		("leaf_index", MIGRATION_HEADER_SIZE + 98, 4),
	];
}

/// ABI layout for the `ListSectionInstruction` instruction.
pub mod instruction_1_09 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:09";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ListSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "122a1c6b6bed60ad958410bc47dde84b93eb8928a46b987347b39f9fc2e36ad4";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 10;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 10;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("price_lamports", MIGRATION_HEADER_SIZE + 2, 8),
	];
}

/// ABI layout for the `CancelSectionListingInstruction` instruction.
pub mod instruction_1_0a {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0a";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CancelSectionListingInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "982e19417c9c992dfbba5efdaebea28d011f34f4adfd2c0332fa73cacc593838";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `PurchaseSectionInstruction` instruction.
pub mod instruction_1_0b {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0b";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "PurchaseSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "01545501ea8a72d610f3426be086a138fc3ac36eecd13ee92ff26f0ba1b03ef4";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 10;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 10;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("maximum_price_lamports", MIGRATION_HEADER_SIZE + 2, 8),
	];
}

/// ABI layout for the `SettleSectionEconomyInstruction` instruction.
pub mod instruction_1_0c {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0c";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SettleSectionEconomyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "982e19417c9c992dfbba5efdaebea28d011f34f4adfd2c0332fa73cacc593838";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `ConfigureBitCustodyInstruction` instruction.
pub mod instruction_1_0d {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0d";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigureBitCustodyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "0964b5ff00a94fb98f2536839ca6abc68a04f31d844cbac2a3aa627a73eeca5a";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `FundSectionVaultInstruction` instruction.
pub mod instruction_1_0e {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0e";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "FundSectionVaultInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "982e19417c9c992dfbba5efdaebea28d011f34f4adfd2c0332fa73cacc593838";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `WithdrawSectionOwnerFeesInstruction` instruction.
pub mod instruction_1_0f {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0f";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "WithdrawSectionOwnerFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "982e19417c9c992dfbba5efdaebea28d011f34f4adfd2c0332fa73cacc593838";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `ConfigureSectionPolicyInstruction` instruction.
pub mod instruction_1_10 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:10";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigureSectionPolicyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "ada581515f27075cee7fc2a598edd1aff39ec94c7a514f135e8b7bab577c86cf";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 77;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 77;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("expected_policy_version", MIGRATION_HEADER_SIZE + 2, 8),
		("mode", MIGRATION_HEADER_SIZE + 10, 1),
		("palette_id", MIGRATION_HEADER_SIZE + 11, 1),
		("reward_policy", MIGRATION_HEADER_SIZE + 12, 1),
		("starts_at", MIGRATION_HEADER_SIZE + 13, 8),
		("ends_at", MIGRATION_HEADER_SIZE + 21, 8),
		("entry_price_tokens", MIGRATION_HEADER_SIZE + 29, 8),
		("reward_per_action_tokens", MIGRATION_HEADER_SIZE + 37, 8),
		("rules_digest", MIGRATION_HEADER_SIZE + 45, 32),
	];
}

/// ABI layout for the `WithdrawProtocolFeesInstruction` instruction.
pub mod instruction_1_11 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:11";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "WithdrawProtocolFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "982e19417c9c992dfbba5efdaebea28d011f34f4adfd2c0332fa73cacc593838";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}
