//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations create`. Do not edit.
//!
//! Run `pina migrations create` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: a51da2a00752618f32e8b14cd982547c81698103c743a09875bfc8e3d06ac468
// program-id: 5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "5AuNvfV9Xi9gskJpW2qQJndQkFcwbWNV6fjaf2VvuEcM";

/// ABI layout for the `ConfigState` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "1864c997503d00f5d99871223156206321d385d891e89935d8b1e4c9f95f8aee";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 236;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 236;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("version", MIGRATION_HEADER_SIZE + 0, 1),
		("authority", MIGRATION_HEADER_SIZE + 1, 32),
		("pending_authority", MIGRATION_HEADER_SIZE + 33, 32),
		("treasury", MIGRATION_HEADER_SIZE + 65, 32),
		("collection_authority", MIGRATION_HEADER_SIZE + 97, 32),
		("bit_mint", MIGRATION_HEADER_SIZE + 129, 32),
		("bit_reserve", MIGRATION_HEADER_SIZE + 161, 32),
		("claim_price_lamports", MIGRATION_HEADER_SIZE + 193, 8),
		("flip_fee_lamports", MIGRATION_HEADER_SIZE + 201, 8),
		("minimum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 209, 8),
		("maximum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 217, 8),
		("unlock_interval_seconds", MIGRATION_HEADER_SIZE + 225, 4),
		("early_unlock_flips", MIGRATION_HEADER_SIZE + 229, 4),
		("game_count", MIGRATION_HEADER_SIZE + 233, 2),
		("bump", MIGRATION_HEADER_SIZE + 235, 1),
	];
}

/// ABI layout for the `GameState` account.
pub mod account_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "GameState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "eed1a5347177216488cae69fbd99aa23bcd7f1ab4d2ef99c9876b50b0a1648dd";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 122;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 122;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("status", MIGRATION_HEADER_SIZE + 1, 1),
		("bump", MIGRATION_HEADER_SIZE + 2, 1),
		("economy_version", MIGRATION_HEADER_SIZE + 3, 1),
		("starts_at", MIGRATION_HEADER_SIZE + 4, 8),
		("next_section", MIGRATION_HEADER_SIZE + 12, 2),
		("minted_sections", MIGRATION_HEADER_SIZE + 14, 2),
		("flip_fee_lamports", MIGRATION_HEADER_SIZE + 16, 8),
		("total_flips", MIGRATION_HEADER_SIZE + 24, 8),
		("section_allocation_tokens", MIGRATION_HEADER_SIZE + 32, 8),
		("emission_duration_seconds", MIGRATION_HEADER_SIZE + 40, 8),
		("window_seconds", MIGRATION_HEADER_SIZE + 48, 8),
		("target_tokens_per_window", MIGRATION_HEADER_SIZE + 56, 8),
		("start_price_lamports", MIGRATION_HEADER_SIZE + 64, 8),
		("minimum_price_lamports", MIGRATION_HEADER_SIZE + 72, 8),
		("maximum_price_lamports", MIGRATION_HEADER_SIZE + 80, 8),
		("start_floor_price_lamports", MIGRATION_HEADER_SIZE + 88, 8),
		("end_floor_price_lamports", MIGRATION_HEADER_SIZE + 96, 8),
		("change_denominator", MIGRATION_HEADER_SIZE + 104, 8),
		("burst_elasticity", MIGRATION_HEADER_SIZE + 112, 8),
		("owner_share_basis_points", MIGRATION_HEADER_SIZE + 120, 2),
	];
}

/// ABI layout for the `SectionState` account.
pub mod account_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SectionState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "7ee436afcdb742586ee5df1dbccd2e2a1bdacce304a9759aaf4b81bc525338e3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 853;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 853;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("owner", MIGRATION_HEADER_SIZE + 0, 32),
		("asset_id", MIGRATION_HEADER_SIZE + 32, 32),
		("merkle_tree", MIGRATION_HEADER_SIZE + 64, 32),
		("bit_vault", MIGRATION_HEADER_SIZE + 96, 32),
		("game_index", MIGRATION_HEADER_SIZE + 128, 1),
		("section_index", MIGRATION_HEADER_SIZE + 129, 1),
		("status", MIGRATION_HEADER_SIZE + 130, 1),
		("bump", MIGRATION_HEADER_SIZE + 131, 1),
		("on_pixels", MIGRATION_HEADER_SIZE + 132, 2),
		("leaf_index", MIGRATION_HEADER_SIZE + 134, 4),
		("flip_count", MIGRATION_HEADER_SIZE + 138, 8),
		("revision", MIGRATION_HEADER_SIZE + 146, 8),
		("last_flip_at", MIGRATION_HEADER_SIZE + 154, 8),
		("sale_price_lamports", MIGRATION_HEADER_SIZE + 162, 8),
		("economy_launched_at", MIGRATION_HEADER_SIZE + 170, 8),
		("economy_window_started_at", MIGRATION_HEADER_SIZE + 178, 8),
		("economy_last_updated_at", MIGRATION_HEADER_SIZE + 186, 8),
		("economy_window_id", MIGRATION_HEADER_SIZE + 194, 8),
		("economy_window_target_tokens", MIGRATION_HEADER_SIZE + 202, 8),
		("economy_window_rewarded_tokens", MIGRATION_HEADER_SIZE + 210, 8),
		("emitted_tokens", MIGRATION_HEADER_SIZE + 218, 8),
		("reward_pool_tokens", MIGRATION_HEADER_SIZE + 226, 8),
		("controller_price_lamports", MIGRATION_HEADER_SIZE + 234, 8),
		("posted_price_lamports", MIGRATION_HEADER_SIZE + 242, 8),
		("protocol_fee_lamports", MIGRATION_HEADER_SIZE + 250, 8),
		("owner_fee_lamports", MIGRATION_HEADER_SIZE + 258, 8),
		("policy_version", MIGRATION_HEADER_SIZE + 266, 8),
		("policy_starts_at", MIGRATION_HEADER_SIZE + 274, 8),
		("policy_ends_at", MIGRATION_HEADER_SIZE + 282, 8),
		("policy_entry_price_tokens", MIGRATION_HEADER_SIZE + 290, 8),
		("policy_reward_per_action_tokens", MIGRATION_HEADER_SIZE + 298, 8),
		("policy_rules_digest", MIGRATION_HEADER_SIZE + 306, 32),
		("policy_mode", MIGRATION_HEADER_SIZE + 338, 1),
		("policy_palette_id", MIGRATION_HEADER_SIZE + 339, 1),
		("policy_reward_policy", MIGRATION_HEADER_SIZE + 340, 1),
		("pixels", MIGRATION_HEADER_SIZE + 341, 512),
	];
}

/// ABI layout for the `ColourPixelsFlippedEvent` event.
pub mod event_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ColourPixelsFlippedEvent";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "d7704b13f224743de5a8cfd4460aee99f29e73f945e825018a8c3dacc47e2e48";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 84;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 84;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("player", MIGRATION_HEADER_SIZE + 0, 32),
		("policy_version", MIGRATION_HEADER_SIZE + 32, 8),
		("revision", MIGRATION_HEADER_SIZE + 40, 8),
		("coordinates", MIGRATION_HEADER_SIZE + 48, 32),
		("game_index", MIGRATION_HEADER_SIZE + 80, 1),
		("section_index", MIGRATION_HEADER_SIZE + 81, 1),
		("count", MIGRATION_HEADER_SIZE + 82, 1),
		("colour", MIGRATION_HEADER_SIZE + 83, 1),
	];
}

/// ABI layout for the `InitializeConfigInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializeConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "3f3f22a55d540fe677d2f3ea9a3ecdc9ddc97436bbbf9e9d5a0974d4dd32e43b";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 1;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 1;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
	];
}

/// ABI layout for the `UpdateConfigInstruction` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "UpdateConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "02200450f0959ae75c5ef8e17b245537785f8e169f5bc4076de1853c14c83375";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 104;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 104;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("treasury", MIGRATION_HEADER_SIZE + 0, 32),
		("collection_authority", MIGRATION_HEADER_SIZE + 32, 32),
		("claim_price_lamports", MIGRATION_HEADER_SIZE + 64, 8),
		("flip_fee_lamports", MIGRATION_HEADER_SIZE + 72, 8),
		("minimum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 80, 8),
		("maximum_flip_fee_lamports", MIGRATION_HEADER_SIZE + 88, 8),
		("unlock_interval_seconds", MIGRATION_HEADER_SIZE + 96, 4),
		("early_unlock_flips", MIGRATION_HEADER_SIZE + 100, 4),
	];
}

/// ABI layout for the `ProposeAuthorityInstruction` instruction.
pub mod instruction_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ProposeAuthorityInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "0661b935056d7609916e00344bf9cadee08a2f68fb8a882f4e6fb2413bb3ac35";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 32;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 32;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("pending_authority", MIGRATION_HEADER_SIZE + 0, 32),
	];
}

/// ABI layout for the `AcceptAuthorityInstruction` instruction.
pub mod instruction_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "AcceptAuthorityInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `InitializeGameInstruction` instruction.
pub mod instruction_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializeGameInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "48fac0ed93730226e50a3a5ab1151f9b965c932f0a10cb03e53ff0142ce465cb";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 4;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 4;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("game_bump", MIGRATION_HEADER_SIZE + 2, 1),
		("section_bump", MIGRATION_HEADER_SIZE + 3, 1),
	];
}

/// ABI layout for the `ClaimSectionInstruction` instruction.
pub mod instruction_1_05 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:05";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ClaimSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "9c9b3b896ae8d6db461e390485d934972c8b2944ba12cae4580f332548695808";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 11;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 11;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("bump", MIGRATION_HEADER_SIZE + 2, 1),
		("maximum_price_lamports", MIGRATION_HEADER_SIZE + 3, 8),
	];
}

/// ABI layout for the `FlipPixelsInstruction` instruction.
pub mod instruction_1_06 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:06";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "FlipPixelsInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "065cb46bf756d19d298c49e0cbffd88435ff8dd32d73af05632286bb9aa7963e";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 76;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 76;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("count", MIGRATION_HEADER_SIZE + 2, 1),
		("coordinates", MIGRATION_HEADER_SIZE + 3, 32),
		("colour", MIGRATION_HEADER_SIZE + 35, 1),
		("expected_policy_version", MIGRATION_HEADER_SIZE + 36, 8),
		("expected_window_id", MIGRATION_HEADER_SIZE + 44, 8),
		("maximum_unit_price_lamports", MIGRATION_HEADER_SIZE + 52, 8),
		("maximum_total_price_lamports", MIGRATION_HEADER_SIZE + 60, 8),
		("minimum_reward_tokens", MIGRATION_HEADER_SIZE + 68, 8),
	];
}

/// ABI layout for the `SealSectionInstruction` instruction.
pub mod instruction_1_07 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:07";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SealSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "707aec15520397032a08ae9b96bdd006a4482dbd22a35926b3ee20cba4360653";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `RecordSectionMintInstruction` instruction.
pub mod instruction_1_08 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:08";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "RecordSectionMintInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "72379a843d7a8438d6a843268dbf37f8f18d1e988c2fb46b04df69a0ecf193b7";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 102;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 102;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("expected_owner", MIGRATION_HEADER_SIZE + 2, 32),
		("asset_id", MIGRATION_HEADER_SIZE + 34, 32),
		("merkle_tree", MIGRATION_HEADER_SIZE + 66, 32),
		("leaf_index", MIGRATION_HEADER_SIZE + 98, 4),
	];
}

/// ABI layout for the `ListSectionInstruction` instruction.
pub mod instruction_1_09 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:09";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ListSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "7a8e55dd3a04d471be27a028fdd9565eba07247a8d6a652942df548f7fe494f0";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 10;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 10;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("price_lamports", MIGRATION_HEADER_SIZE + 2, 8),
	];
}

/// ABI layout for the `CancelSectionListingInstruction` instruction.
pub mod instruction_1_0a {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0a";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CancelSectionListingInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "707aec15520397032a08ae9b96bdd006a4482dbd22a35926b3ee20cba4360653";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `PurchaseSectionInstruction` instruction.
pub mod instruction_1_0b {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0b";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "PurchaseSectionInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "521c51b10ec412088ad988e912ffb38745e8dada824294fa2b6dfe741ddac592";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 10;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 10;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("maximum_price_lamports", MIGRATION_HEADER_SIZE + 2, 8),
	];
}

/// ABI layout for the `SettleSectionEconomyInstruction` instruction.
pub mod instruction_1_0c {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0c";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SettleSectionEconomyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "707aec15520397032a08ae9b96bdd006a4482dbd22a35926b3ee20cba4360653";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `ConfigureBitCustodyInstruction` instruction.
pub mod instruction_1_0d {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0d";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigureBitCustodyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `FundSectionVaultInstruction` instruction.
pub mod instruction_1_0e {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0e";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "FundSectionVaultInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "707aec15520397032a08ae9b96bdd006a4482dbd22a35926b3ee20cba4360653";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `WithdrawSectionOwnerFeesInstruction` instruction.
pub mod instruction_1_0f {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:0f";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "WithdrawSectionOwnerFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "707aec15520397032a08ae9b96bdd006a4482dbd22a35926b3ee20cba4360653";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

/// ABI layout for the `ConfigureSectionPolicyInstruction` instruction.
pub mod instruction_1_10 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:10";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigureSectionPolicyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "73ce235f38a27ac07e0181d854ca0af8f7e04d991d0b105089454229937cc5dc";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 77;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 77;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
		("expected_policy_version", MIGRATION_HEADER_SIZE + 2, 8),
		("mode", MIGRATION_HEADER_SIZE + 10, 1),
		("palette_id", MIGRATION_HEADER_SIZE + 11, 1),
		("reward_policy", MIGRATION_HEADER_SIZE + 12, 1),
		("starts_at", MIGRATION_HEADER_SIZE + 13, 8),
		("ends_at", MIGRATION_HEADER_SIZE + 21, 8),
		("entry_price_tokens", MIGRATION_HEADER_SIZE + 29, 8),
		("reward_per_action_tokens", MIGRATION_HEADER_SIZE + 37, 8),
		("rules_digest", MIGRATION_HEADER_SIZE + 45, 32),
	];
}

/// ABI layout for the `WithdrawProtocolFeesInstruction` instruction.
pub mod instruction_1_11 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:11";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "WithdrawProtocolFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "707aec15520397032a08ae9b96bdd006a4482dbd22a35926b3ee20cba4360653";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("game_index", MIGRATION_HEADER_SIZE + 0, 1),
		("section_index", MIGRATION_HEADER_SIZE + 1, 1),
	];
}

