name: "ci"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  ADMIN_PUBKEY: 4z5X2suocz9szaQnSshj2AW8tuLgUVmYUxiW9hhPaRHs

jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: lint formatting
        run: bitflip lint:format
        shell: bash

      - name: lint formatting
        run: bitflip lint:deno
        shell: bash

      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-features

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - test_program
          - test_bitflip_ssr
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: test ${{ matrix.test }}
        run: cargo ${{ matrix.test }}
        shell: bash

  build_bitflip_program:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: build
        run: bitflip build:program
        shell: bash

      - name: upload bitflip program
        uses: actions/upload-artifact@v4
        with:
          name: bitflip_program.so
          path: target/deploy/bitflip_program.so

  test_program_with_validator:
    timeout-minutes: 60
    needs: [build_bitflip_program]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: download bitflip program
        uses: actions/download-artifact@v4
        with:
          name: bitflip_program.so
          path: target/deploy/bitflip_program.so

      - name: test
        run: cargo test_program_validator
        shell: bash

  build_bitflip_website:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: build
        run: bitflip build
        shell: bash
