name: "ci"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    timeout-minutes: 60
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: lint formatting
        run: lint:format
        shell: bash

      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-features

  build_bitflip:
    timeout-minutes: 60
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: build
        run: anchor:build
        shell: bash

  build_bitflip_website:
    timeout-minutes: 60
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          deno-cache: /tmp/denocache

      - name: build
        run: build:bitflip
        shell: bash
